config/routes.rb
CollaBoard::Application.routes.draw do
  get "/" => "dashboard#index"
  get "/dashboard" => "dashboard#index"
  get "/dashboard/index" => "dashboard#index"

  get "sign_up" => redirect("auth/yammer")
  get "sign_in" => redirect("/auth/yammer")

  get "auth/failure" => "sessions#failure"
  get "sign_out" => "sessions#destroy", as: :sign_out
  get "/auth/:provider/callback" => 'sessions#create'
  post "/auth/:provider/callback" => 'sessions#create'

  resources :users, only: [:index, :show]
  resources :projects do
    resources :tasks, except: [:destroy] do
      member do
        get 'comments'
        post 'add_comment'
      end
    end
  end

  root to: "dashboard#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :task, :author, :content
  belongs_to :author, class_name: "User"
  belongs_to :task
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates_presence_of :title
  has_many :tasks, -> { order("urgent DESC, updated_at DESC") }

  scope :normal, -> { where(archived: false) }
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates_presence_of :subject, :urgent, :project_id, :author_id

  STATUS = %w[todo doing completed accepted]

  belongs_to :project
  belongs_to :author, class_name: "User"
  belongs_to :assignee, class_name: "User"
  belongs_to :reviewer, class_name: "User"
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :email, :name, :avatar, :yammer_uid

  has_many :comments
  has_many :tasks, -> { order("urgent DESC, updated_at DESC") },
    foreign_key: "author_id"
  has_many :review_tasks, -> { order("urgent DESC, updated_at DESC") },
    class_name: "Task", foreign_key: "reviewer_id"
  has_many :todo_tasks, -> { order("urgent DESC, updated_at DESC") },
    class_name: "Task", foreign_key: "assignee_id"

  def self.find_or_create_from_auth_hash auth_hash
    user_attributes = {
      email: auth_hash.info.email,
      avatar: auth_hash.info.image,
      name: auth_hash.info.name,
      yammer_uid: auth_hash.uid
    }

    if user = User.find_by_email(user_attributes[:email])
      user.update_attributes user_attributes.slice(:avatar, :name, :yammer_uid)
    else
      return nil unless user_attributes[:email].end_with?("@hzuwando.com")
      user = create! user_attributes
    end

    user
  end

  def self.find_by_email_and_return_id(_email)
    where(email: _email).first.try(:id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include UserAuthentication
  before_action :login_required

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/user_authentication.rb
module UserAuthentication
  def self.included(base)
    base.helper_method :current_user, :signed_in?
  end

  def current_user
    unless session[:user_id].blank?
      @current_user ||= User.find_by id: session[:user_id]
    end
    @current_user
  end

  def signed_in?
    !!current_user
  end

  def login_required
    redirect_to sign_in_path unless signed_in?
  end

  def sign_in user
    session[:user_id] = user.id
  end

  def sign_out
    session[:user_id] = nil
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  # GET /projects
  def index
    @projects = Project.normal.page(params[:page]).per(15)
  end

  # GET /projects/:id
  def show
    @project = Project.find params[:id]
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # POST /projects
  def create
    @project = Project.new project_param
    if @project.save
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  # GET /projects/:id/edit
  def edit
    @project = Project.find params[:id]
  end

  # PATCH /projects/:id
  def update
    @project = Project.find params[:id]
    if @project.update project_param
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  private
  def project_param
    params.require(:project).permit(:title, :description, :archived)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  protect_from_forgery with: :null_session
  skip_before_action :login_required

  def create
    if user = User.find_or_create_from_auth_hash(auth_hash)
      sign_in user
      redirect_to :root
    else
      redirect_to "/auth/failure"
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  def failure
    sign_out
    render layout: false
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  # GET /tasks
  def index
  end

  # GET /tasks/:id
  def show
  end

  # GET /tasks/new
  def new
  end

  # POST /tasks
  def create
  end

  # GET /tasks/:id/edit
  def edit
  end

  # PATCH /tasks/:id
  def update
  end

  # GET /tasks/:id/comments
  def comments
  end

  # POST /tasks/:id/add_comment
  def add_comment
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/:id
  def show
    @user = User.find params[:id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
Hello World

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? "#{yield(:title)} | " : "" %>Colla</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>
  <div class="navbar navbar-inverse app-header">
    <div class="navbar-inner">
      <div class="container">
       
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
       
        <a class="brand" href="/">Colla</a>
       
        <div class="nav-collapse collapse">
          <ul class="nav">
            <li><%= link_to "项目", projects_path, class: "nav-link" %></li>
            <li><%= link_to "用户", users_path, class: "nav-link" %></li>
          </ul>
          <ul class="nav pull-right">
            <li class="nav-avatar">
              <a href="<%= user_path(current_user) %>" class="avatar" style="padding: 0 15px;">
                <%= image_tag current_user.avatar %>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div id="site-main-wrapper">
    <%= yield %>
  </div>
</body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for project,
  url: project.new_record? ? projects_path : project_path(project),
  html: { class: "form-horizontal" } do |f| %>

  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :archived %>

  <div class="control-group">
    <div class="controls">
      <%= f.button :submit %>
    </div>
  </div>

<% end %>

app/views/projects/edit.html.erb
<% content_for :title do %>编辑项目<% end %>

<%= render "form", project: @project %>

app/views/projects/index.html.erb
<% content_for :title do %>项目列表<% end %>

<div class="actions-bar">
  <%= link_to "新增项目", new_project_path, class: "btn" %>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Created At</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |p| %>
      <tr>
        <td><%= link_to p.title, project_path(p) %></td>
        <td><%= p.description %></td>
        <td><%= p.created_at.to_s %></td>
        <td>
          <%= link_to "Show", project_path(p) %>
          <%= link_to "Edit", edit_project_path(p) %>
        </td>
      </tr>
    <% end %>
  </tbody>
  </table>
<%= paginate @projects %>

app/views/projects/new.html.erb
<% content_for :title do %>新增项目<% end %>

<%= render "form", project: @project %>

app/views/projects/show.html.erb
<% content_for :title do %>项目详情<% end %>

<div>List tasks here by using table view</div>

app/views/users/index.html.erb
<ul class="thumbnails" id="users-wrapper">
  <% @users.each do |user| %>
    <li class="span3">
      <a href="<%= user_path(user) %>" class="thumbnail">
        <%= image_tag user.avatar %>
        <div class="name"><%= user.name %></div>
      </a>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<% content_for :title do %><%= @user.name %><% end %>

<div>Please list the tasks belongs to this user</div>
<div>Include review & todo tasks</div>